"""add user account lockout columns

Revision ID: 360f466a2599
Revises: 3095ed4e6bc9
Create Date: 2026-03-30 19:38:08.842773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '360f466a2599'
down_revision = '3095ed4e6bc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_events', schema=None) as batch_op:
        batch_op.create_index('idx_parking_events_slot_time', ['slot_id', 'timestamp'], unique=False)
        batch_op.create_index('idx_parking_events_timestamp', ['timestamp'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed_login_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('locked_until', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('locked_until')
        batch_op.drop_column('failed_login_count')

    with op.batch_alter_table('parking_events', schema=None) as batch_op:
        batch_op.drop_index('idx_parking_events_timestamp')
        batch_op.drop_index('idx_parking_events_slot_time')

    # ### end Alembic commands ###
