"""initial schema for day1 foundation

Revision ID: ac67284e56b9
Revises: 
Create Date: 2026-02-27 17:20:25.983430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac67284e56b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parking_lots',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('total_slots', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('zones',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('lot_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('walk_times', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['parking_lots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lot_id', 'name', name='uq_zone_lot_name')
    )
    op.create_table('parking_slots',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('lot_id', sa.String(length=50), nullable=False),
    sa.Column('zone_id', sa.String(length=50), nullable=True),
    sa.Column('slot_number', sa.Integer(), nullable=False),
    sa.Column('is_occupied', sa.Boolean(), nullable=True),
    sa.Column('is_reserved', sa.Boolean(), nullable=True),
    sa.Column('slot_type', sa.String(length=20), nullable=True),
    sa.Column('sensor_id', sa.String(length=50), nullable=True),
    sa.Column('last_status_change', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lot_id'], ['parking_lots.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('occupancy_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('distance_cm', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['slot_id'], ['parking_slots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('occupancy_logs', schema=None) as batch_op:
        batch_op.create_index('idx_occupancy_logs_slot_time', ['slot_id', 'timestamp'], unique=False)

    op.create_table('parking_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('sensor_distance_cm', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['slot_id'], ['parking_slots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.String(length=50), nullable=False),
    sa.Column('distance_cm', sa.Float(), nullable=False),
    sa.Column('is_occupied', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['slot_id'], ['parking_slots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sensor_readings', schema=None) as batch_op:
        batch_op.create_index('idx_sensor_readings_slot_time', ['slot_id', 'timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor_readings', schema=None) as batch_op:
        batch_op.drop_index('idx_sensor_readings_slot_time')

    op.drop_table('sensor_readings')
    op.drop_table('parking_events')
    with op.batch_alter_table('occupancy_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_occupancy_logs_slot_time')

    op.drop_table('occupancy_logs')
    op.drop_table('parking_slots')
    op.drop_table('zones')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('parking_lots')
    # ### end Alembic commands ###
